"""add instrument figi columns

Revision ID: 0873d0d3f871
Revises: c9bb4d8cd815
Create Date: 2026-09-17 22:12:23.915165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0873d0d3f871'
down_revision: Union[str, Sequence[str], None] = 'c9bb4d8cd815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('figi', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('share_class_figi', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('figi_checked_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_instruments_figi'), ['figi'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_share_class_figi'), ['share_class_figi'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_share_class_figi'))
        batch_op.drop_index(batch_op.f('ix_instruments_figi'))
        batch_op.drop_column('figi_checked_at')
        batch_op.drop_column('share_class_figi')
        batch_op.drop_column('figi')

    # ### end Alembic commands ###
