"""widen provider_usage.period_key to 16 chars

Revision ID: 0d3b4d0b7753
Revises: 0e2d12aac3d0
Create Date: 2026-08-22 00:27:39.037495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3b4d0b7753'
down_revision: Union[str, Sequence[str], None] = '0e2d12aac3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_usage', schema=None) as batch_op:
        batch_op.alter_column('period_key',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_usage', schema=None) as batch_op:
        batch_op.alter_column('period_key',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
