"""add screener_candidates table

Revision ID: 0e2d12aac3d0
Revises: 39575e46f410
Create Date: 2026-08-22 00:09:03.572067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2d12aac3d0'
down_revision: Union[str, Sequence[str], None] = '39575e46f410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screener_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screener_candidates_instrument_id'), 'screener_candidates', ['instrument_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screener_candidates_instrument_id'), table_name='screener_candidates')
    op.drop_table('screener_candidates')
    # ### end Alembic commands ###
