"""add personal policy and policy limits

Revision ID: 0f3df0ede51c
Revises: 0f34b2035767
Create Date: 2026-09-10 02:32:54.647056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3df0ede51c'
down_revision: Union[str, Sequence[str], None] = '0f34b2035767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective_growth', sa.Boolean(), nullable=False),
    sa.Column('objective_income', sa.Boolean(), nullable=False),
    sa.Column('objective_preservation', sa.Boolean(), nullable=False),
    sa.Column('objective_note', sa.String(length=500), nullable=True),
    sa.Column('horizon', sa.String(length=20), nullable=True),
    sa.Column('horizon_target_date', sa.Date(), nullable=True),
    sa.Column('liquidity_need_amount', sa.Float(), nullable=True),
    sa.Column('liquidity_need_date', sa.Date(), nullable=True),
    sa.Column('liquidity_note', sa.String(length=500), nullable=True),
    sa.Column('risk_tolerance_note', sa.String(length=500), nullable=True),
    sa.Column('loss_capacity_pct', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_policy_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=80), nullable=True),
    sa.Column('min_pct', sa.Float(), nullable=True),
    sa.Column('max_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension', 'target', name='uq_policy_limit_dimension_target')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_policy_limits')
    op.drop_table('personal_policy')
    # ### end Alembic commands ###
