"""add amundi fund snapshot history

Revision ID: 1be94478a200
Revises: 2bccf46c5433
Create Date: 2026-09-08 13:32:45.269485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be94478a200'
down_revision: Union[str, Sequence[str], None] = '2bccf46c5433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amundi_fund_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_symbol', sa.String(length=40), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('gross_value', sa.Float(), nullable=False),
    sa.Column('estimated_gain_loss', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_symbol', 'as_of', name='uq_amundi_fund_snapshot')
    )
    with op.batch_alter_table('amundi_fund_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amundi_fund_snapshots_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_amundi_fund_snapshots_broker_symbol'), ['broker_symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amundi_fund_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amundi_fund_snapshots_broker_symbol'))
        batch_op.drop_index(batch_op.f('ix_amundi_fund_snapshots_as_of'))

    op.drop_table('amundi_fund_snapshots')
    # ### end Alembic commands ###
