"""baseline schema

Revision ID: 39575e46f410
Revises: 
Create Date: 2026-08-20 22:28:38.523227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39575e46f410'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_price_refresh_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'base_currency', 'rate_date', name='uq_fx_rate')
    )
    op.create_index(op.f('ix_fx_rates_currency'), 'fx_rates', ['currency'], unique=False)
    op.create_index(op.f('ix_fx_rates_rate_date'), 'fx_rates', ['rate_date'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('positions_found', sa.Integer(), nullable=False),
    sa.Column('transactions_found', sa.Integer(), nullable=False),
    sa.Column('transactions_inserted', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('accounts', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_file_hash'), 'import_batches', ['file_hash'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_symbol', sa.String(length=40), nullable=False),
    sa.Column('provider_symbol', sa.String(length=40), nullable=True),
    sa.Column('mapping_status', sa.String(length=20), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('exchange', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_provider', sa.String(length=30), nullable=True),
    sa.Column('not_priceable_reason', sa.String(length=40), nullable=True),
    sa.Column('prices_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_broker_symbol'), 'instruments', ['broker_symbol'], unique=True)
    op.create_index(op.f('ix_instruments_category'), 'instruments', ['category'], unique=False)
    op.create_index(op.f('ix_instruments_isin'), 'instruments', ['isin'], unique=False)
    op.create_index(op.f('ix_instruments_provider_symbol'), 'instruments', ['provider_symbol'], unique=False)
    op.create_table('provider_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('period_key', sa.String(length=16), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'period_key', name='uq_provider_usage_period')
    )
    op.create_index(op.f('ix_provider_usage_provider'), 'provider_usage', ['provider'], unique=False)
    op.create_table('symbol_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_symbol', sa.String(length=40), nullable=False),
    sa.Column('provider_symbol', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_overrides_broker_symbol'), 'symbol_overrides', ['broker_symbol'], unique=True)
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=40), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('tag', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'concept', 'fiscal_year', name='uq_fundamental')
    )
    op.create_index(op.f('ix_fundamentals_concept'), 'fundamentals', ['concept'], unique=False)
    op.create_index(op.f('ix_fundamentals_fiscal_year'), 'fundamentals', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_fundamentals_instrument_id'), 'fundamentals', ['instrument_id'], unique=False)
    op.create_table('last_quotes',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('lot_type', sa.String(length=10), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'lot_type', name='uq_lot_external')
    )
    op.create_index(op.f('ix_lots_account'), 'lots', ['account'], unique=False)
    op.create_index(op.f('ix_lots_closed_at'), 'lots', ['closed_at'], unique=False)
    op.create_index(op.f('ix_lots_external_id'), 'lots', ['external_id'], unique=False)
    op.create_index(op.f('ix_lots_instrument_id'), 'lots', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_lots_lot_type'), 'lots', ['lot_type'], unique=False)
    op.create_index(op.f('ix_lots_opened_at'), 'lots', ['opened_at'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('account', sa.String(length=40), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('lots_count', sa.Integer(), nullable=False),
    sa.Column('broker_gross_pl', sa.Float(), nullable=True),
    sa.Column('broker_net_pl', sa.Float(), nullable=True),
    sa.Column('broker_net_pl_pct', sa.Float(), nullable=True),
    sa.Column('broker_purchase_value', sa.Float(), nullable=True),
    sa.Column('broker_market_value', sa.Float(), nullable=True),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('swap', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_account'), 'positions', ['account'], unique=False)
    op.create_index(op.f('ix_positions_external_id'), 'positions', ['external_id'], unique=False)
    op.create_index(op.f('ix_positions_instrument_id'), 'positions', ['instrument_id'], unique=False)
    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('bar_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'bar_date', name='uq_bar')
    )
    op.create_index(op.f('ix_price_bars_bar_date'), 'price_bars', ['bar_date'], unique=False)
    op.create_index(op.f('ix_price_bars_instrument_id'), 'price_bars', ['instrument_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('swap', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'type', name='uq_tx_external')
    )
    op.create_index(op.f('ix_transactions_executed_at'), 'transactions', ['executed_at'], unique=False)
    op.create_index(op.f('ix_transactions_external_id'), 'transactions', ['external_id'], unique=False)
    op.create_index(op.f('ix_transactions_instrument_id'), 'transactions', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('target_entry_price', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_items_instrument_id'), 'watchlist_items', ['instrument_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_instrument_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_instrument_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_executed_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_price_bars_instrument_id'), table_name='price_bars')
    op.drop_index(op.f('ix_price_bars_bar_date'), table_name='price_bars')
    op.drop_table('price_bars')
    op.drop_index(op.f('ix_positions_instrument_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_external_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_account'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_lots_opened_at'), table_name='lots')
    op.drop_index(op.f('ix_lots_lot_type'), table_name='lots')
    op.drop_index(op.f('ix_lots_instrument_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_external_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_closed_at'), table_name='lots')
    op.drop_index(op.f('ix_lots_account'), table_name='lots')
    op.drop_table('lots')
    op.drop_table('last_quotes')
    op.drop_index(op.f('ix_fundamentals_instrument_id'), table_name='fundamentals')
    op.drop_index(op.f('ix_fundamentals_fiscal_year'), table_name='fundamentals')
    op.drop_index(op.f('ix_fundamentals_concept'), table_name='fundamentals')
    op.drop_table('fundamentals')
    op.drop_index(op.f('ix_symbol_overrides_broker_symbol'), table_name='symbol_overrides')
    op.drop_table('symbol_overrides')
    op.drop_index(op.f('ix_provider_usage_provider'), table_name='provider_usage')
    op.drop_table('provider_usage')
    op.drop_index(op.f('ix_instruments_provider_symbol'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_isin'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_category'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_broker_symbol'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_import_batches_file_hash'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_fx_rates_rate_date'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_currency'), table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_table('app_metadata')
    # ### end Alembic commands ###
