"""add bytes_used to provider_usage

Revision ID: 5075c1a6b378
Revises: a03cd2a8e52b
Create Date: 2026-09-07 12:30:13.045369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5075c1a6b378'
down_revision: Union[str, Sequence[str], None] = 'a03cd2a8e52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bytes_used', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_usage', schema=None) as batch_op:
        batch_op.drop_column('bytes_used')

    # ### end Alembic commands ###
