"""add account to transactions

Revision ID: 541e116a92d3
Revises: 7a4f383ab9ea
Create Date: 2026-09-05 15:10:04.047292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541e116a92d3'
down_revision: Union[str, Sequence[str], None] = '7a4f383ab9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_account'), ['account'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_account'))
        batch_op.drop_column('account')

    # ### end Alembic commands ###
