"""add discovery_candidates table

Revision ID: 5b1537197d7f
Revises: 7a84bd95ca78
Create Date: 2026-08-28 00:07:25.700027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1537197d7f'
down_revision: Union[str, Sequence[str], None] = '7a84bd95ca78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovery_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_candidates_instrument_id'), ['instrument_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovery_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_candidates_instrument_id'))

    op.drop_table('discovery_candidates')
    # ### end Alembic commands ###
