"""add factor_returns table

Revision ID: 7a4f383ab9ea
Revises: 5b1537197d7f
Create Date: 2026-09-03 02:18:28.089740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4f383ab9ea'
down_revision: Union[str, Sequence[str], None] = '5b1537197d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factor_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('mkt_rf', sa.Float(), nullable=False),
    sa.Column('smb', sa.Float(), nullable=False),
    sa.Column('hml', sa.Float(), nullable=False),
    sa.Column('mom', sa.Float(), nullable=False),
    sa.Column('rf', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region', 'return_date')
    )
    with op.batch_alter_table('factor_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factor_returns_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_factor_returns_return_date'), ['return_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factor_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factor_returns_return_date'))
        batch_op.drop_index(batch_op.f('ix_factor_returns_region'))

    op.drop_table('factor_returns')
    # ### end Alembic commands ###
