"""add allocation_targets table

Revision ID: 7a84bd95ca78
Revises: e3a0ccc4dd0b
Create Date: 2026-08-25 00:48:54.582525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a84bd95ca78'
down_revision: Union[str, Sequence[str], None] = 'e3a0ccc4dd0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('min_pct', sa.Float(), nullable=False),
    sa.Column('max_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allocation_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocation_targets_category'), ['category'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocation_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocation_targets_category'))

    op.drop_table('allocation_targets')
    # ### end Alembic commands ###
