"""add corporate action candidates, confidence, fmp splits status

Revision ID: 84da6531c429
Revises: ec8ac9461e7a
Create Date: 2026-09-07 23:37:04.480534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84da6531c429'
down_revision: Union[str, Sequence[str], None] = 'ec8ac9461e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_corporate_action_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('numerator', sa.Float(), nullable=True),
    sa.Column('denominator', sa.Float(), nullable=True),
    sa.Column('economic_factor', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('provider_status', sa.String(length=20), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'provider', 'event_date', name='uq_candidate_instrument_provider_date')
    )
    with op.batch_alter_table('provider_corporate_action_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_corporate_action_candidates_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_corporate_action_candidates_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_corporate_action_candidates_provider'), ['provider'], unique=False)

    with op.batch_alter_table('app_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fmp_splits_status', sa.String(length=20), nullable=False, server_default='recovering'))

    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.String(length=24), nullable=False, server_default='manual'))
        batch_op.add_column(sa.Column('corroborating_sources', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.drop_column('corroborating_sources')
        batch_op.drop_column('confidence')

    with op.batch_alter_table('app_metadata', schema=None) as batch_op:
        batch_op.drop_column('fmp_splits_status')

    with op.batch_alter_table('provider_corporate_action_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_corporate_action_candidates_provider'))
        batch_op.drop_index(batch_op.f('ix_provider_corporate_action_candidates_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_provider_corporate_action_candidates_event_date'))

    op.drop_table('provider_corporate_action_candidates')
    # ### end Alembic commands ###
