"""add corporate action resume run tracking and pause toggle

Revision ID: 939b1bed663a
Revises: 84da6531c429
Create Date: 2026-09-08 00:32:45.005403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '939b1bed663a'
down_revision: Union[str, Sequence[str], None] = '84da6531c429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_action_resume_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('skipped_reason', sa.String(length=30), nullable=True),
    sa.Column('targeted_instrument_ids', sa.JSON(), nullable=False),
    sa.Column('checked', sa.Integer(), nullable=False),
    sa.Column('rate_limited', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('no_events', sa.Integer(), nullable=False),
    sa.Column('verified_three_sources', sa.Integer(), nullable=False),
    sa.Column('verified_cross_source', sa.Integer(), nullable=False),
    sa.Column('candidate_single_source', sa.Integer(), nullable=False),
    sa.Column('provider_conflict', sa.Integer(), nullable=False),
    sa.Column('suspect_ticker_reuse', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('remaining_incomplete', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corporate_action_resume_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporate_action_resume_runs_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_corporate_action_resume_runs_started_at'), ['started_at'], unique=False)

    with op.batch_alter_table('app_metadata', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('alpha_vantage_resume_enabled', sa.Boolean(), nullable=False, server_default=sa.true())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_metadata', schema=None) as batch_op:
        batch_op.drop_column('alpha_vantage_resume_enabled')

    with op.batch_alter_table('corporate_action_resume_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporate_action_resume_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_corporate_action_resume_runs_provider'))

    op.drop_table('corporate_action_resume_runs')
    # ### end Alembic commands ###
