"""add corporate actions table

Revision ID: a03cd2a8e52b
Revises: 541e116a92d3
Create Date: 2026-09-05 23:45:35.050434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03cd2a8e52b'
down_revision: Union[str, Sequence[str], None] = '541e116a92d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('ratio_numerator', sa.Float(), nullable=False),
    sa.Column('ratio_denominator', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_reference', sa.String(length=200), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('price_history_status', sa.String(length=20), nullable=False),
    sa.Column('detected_price_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporate_actions_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_corporate_actions_instrument_id'), ['instrument_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporate_actions_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_corporate_actions_effective_date'))

    op.drop_table('corporate_actions')
    # ### end Alembic commands ###
