"""add discovery candidate dividend checked at

Revision ID: c9bb4d8cd815
Revises: 75e668ef8794
Create Date: 2026-09-17 21:12:32.170855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9bb4d8cd815'
down_revision: Union[str, Sequence[str], None] = '75e668ef8794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovery_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dividend_checked_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovery_candidates', schema=None) as batch_op:
        batch_op.drop_column('dividend_checked_at')

    # ### end Alembic commands ###
