"""add corporate_actions_checked_at to instruments

Revision ID: ec8ac9461e7a
Revises: 5075c1a6b378
Create Date: 2026-09-07 12:36:32.166809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8ac9461e7a'
down_revision: Union[str, Sequence[str], None] = '5075c1a6b378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('corporate_actions_checked_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_column('corporate_actions_checked_at')

    # ### end Alembic commands ###
